#!/usr/bin/env node
/**
 * Renders the screened photographs into the two sizes the site serves, and
 * writes the index the gallery and the diary both read.
 *
 * These do not go through astro:assets: a thousand images would make every
 * build crawl, and they never change once written. Output lands in public/
 * as finished WebP, named by the photo's own date so the URL is legible.
 *
 *   node scripts/build-photos.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

const FULL = 1200, THUMB = 400;
const drafts = JSON.parse(readFileSync('diary/drafts.json', 'utf8'));
const dirOf = new Map();
for (const d of drafts) for (const m of d.media) dirOf.set(m.file, m.dir);

const days = JSON.parse(readFileSync('diary/screened.json', 'utf8'));
const index = [];

for (const day of days) {
  if (!day.picks.length) continue;
  const month = day.date.slice(0, 7);
  const dir = join('public/photos', month);
  mkdirSync(dir, { recursive: true });

  for (const [i, p] of day.picks.entries()) {
    // Named by date and position, not by WhatsApp's filename: those carry the
    // date the export ran, which is not the date the photo was taken.
    const id = `${day.date}-${String(i + 1).padStart(2, '0')}`;
    const src = join(dirOf.get(p.file), p.file);
    const full = join(dir, `${id}.webp`);
    const thumb = join(dir, `${id}-t.webp`);

    let meta;
    if (!existsSync(full)) {
      meta = await sharp(src).rotate().resize(FULL, FULL, { fit: 'inside', withoutEnlargement: true })
        .webp({ quality: 68 }).toFile(full);
      await sharp(src).rotate().resize(THUMB, THUMB, { fit: 'cover' }).webp({ quality: 62 }).toFile(thumb);
    } else {
      meta = await sharp(full).metadata();
    }

    index.push({
      id,
      date: day.date,
      month,
      time: p.time,
      width: meta.width,
      height: meta.height,
      /** Portrait frames get a taller cell in the grid. */
      tall: meta.height > meta.width * 1.15,
    });
  }
}

const ts = `// Generated by scripts/build-photos.mjs — do not edit by hand.
// One entry per photograph in public/photos/, in date order.

export interface Photo {
  /** Also the filename: public/photos/<month>/<id>.webp and <id>-t.webp */
  id: string;
  date: string;
  month: string;
  time: string;
  width: number;
  height: number;
  tall: boolean;
}

export const photos: Photo[] = ${JSON.stringify(index, null, 2)};

/** Every month that has photographs, newest first. */
export const months = [...new Set(photos.map((p) => p.month))].sort().reverse();

/**
 * How many times the club has met, counted as days with three or more
 * photographs — enough to say a run happened rather than someone posting a
 * picture. Widen or narrow it here and every page that shows the number follows.
 */
export const meetUps = [...new Set(photos.map((p) => p.date))].filter(
  (date) => photos.filter((p) => p.date === date).length >= 3
).length;
`;
writeFileSync('src/data/library.ts', ts);
console.log(`${index.length} photographs into public/photos/, index at src/data/library.ts`);
