#!/usr/bin/env node
/**
 * Finds photographs of the same moment, and picks one of each.
 *
 * The first pass in curate-photos.mjs used a perceptual hash alone and only
 * caught rapid-fire bursts. It missed the common case: two people photographing
 * the same group from slightly different spots, seconds apart. Those come out
 * 18-22 apart by hash, and genuinely different photos of the same place come
 * out 24 — too close to separate safely.
 *
 * What does separate them is colour layout: the mean difference between two
 * 8x8 RGB thumbnails. The same moment scores 12-24; different photos of the
 * same scene, even the same people in the same place minutes apart, score 28
 * and up. The threshold sits in that gap.
 *
 * Two rules learned the hard way. A photo joins a group only if it is close to
 * every photo already in it — matching any one member chains A to B to C until
 * a picture of somebody walking has swallowed five different group photos, and
 * matching only the first lets the group drift away from it. And keep the
 * sharpest of a group, so a blurred frame never wins.
 *
 * Writes src/data/similar.ts — the ones to leave out of the diary. Nothing is
 * deleted, and the gallery still shows everything.
 *
 *   node scripts/find-similar.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import sharp from 'sharp';

const COLOUR_LIMIT = 25; // mean 0-255 difference across an 8x8 RGB thumbnail
const HASH_LIMIT = 24;   // and the hash must broadly agree

const lib = readFileSync('src/data/library.ts', 'utf8');
const MARKER = 'export const photos: Photo[] = ';
const start = lib.indexOf(MARKER) + MARKER.length;
const photos = JSON.parse(lib.slice(start, lib.indexOf('\n];', start) + 2));
const path = (p) => `public/photos/${p.month}/${p.id}.webp`;

async function signature(file) {
  const img = sharp(file).rotate();
  const colour = await img.clone().resize(8, 8, { fit: 'fill' }).removeAlpha().raw().toBuffer();
  const grey = await img.clone().greyscale().resize(9, 8, { fit: 'fill' }).raw().toBuffer();
  let hash = 0n;
  for (let y = 0; y < 8; y++)
    for (let x = 0; x < 8; x++) hash = (hash << 1n) | (grey[y * 9 + x] > grey[y * 9 + x + 1] ? 1n : 0n);
  // Sharpness decides which of a pair survives.
  const s = await img.clone().greyscale().resize(160, 160, { fit: 'fill' }).raw().toBuffer();
  let sum = 0, sq = 0, n = 0;
  for (let y = 1; y < 159; y++)
    for (let x = 1; x < 159; x++) {
      const i = y * 160 + x;
      const l = 4 * s[i] - s[i - 1] - s[i + 1] - s[i - 160] - s[i + 160];
      sum += l; sq += l * l; n++;
    }
  return { colour, hash, sharpness: sq / n - (sum / n) ** 2 };
}

const colourDistance = (a, b) => {
  let total = 0;
  for (let i = 0; i < a.length; i++) total += Math.abs(a[i] - b[i]);
  return total / a.length;
};

const hamming = (a, b) => {
  let v = a ^ b, n = 0;
  while (v) { n += Number(v & 1n); v >>= 1n; }
  return n;
};

const byDay = new Map();
for (const p of photos) {
  if (!byDay.has(p.date)) byDay.set(p.date, []);
  byDay.get(p.date).push(p);
}

const dropped = [];
const groups = [];
for (const [date, day] of byDay) {
  const sigs = [];
  for (const p of day) sigs.push({ ...p, ...(await signature(path(p))) });

  const clusters = [];
  for (const p of sigs) {
    // Against every member — see the note above about chaining and drift.
    const hit = clusters.find((c) =>
      c.every((o) => colourDistance(o.colour, p.colour) < COLOUR_LIMIT && hamming(o.hash, p.hash) <= HASH_LIMIT)
    );
    if (hit) hit.push(p); else clusters.push([p]);
  }

  for (const c of clusters) {
    if (c.length === 1) continue;
    const keep = c.slice().sort((a, b) => b.sharpness - a.sharpness)[0];
    groups.push({ date, keep: keep.id, drop: c.filter((p) => p !== keep).map((p) => p.id) });
    for (const p of c) if (p !== keep) dropped.push(p.id);
  }
}

writeFileSync(
  'src/data/similar.ts',
  `// Generated by scripts/find-similar.mjs — do not edit by hand.
//
// Photographs of a moment already shown by another photograph. Kept out of the
// diary only; the gallery still has them, and the files are untouched.
//
// ${dropped.length} of ${photos.length} photographs, from ${groups.length} groups.

export const similarToOthers = new Set<string>(${JSON.stringify(dropped, null, 2)});
`
);

console.log(`${groups.length} groups of the same moment, ${dropped.length} photographs set aside`);
console.log('biggest groups:');
for (const g of groups.sort((a, b) => b.drop.length - a.drop.length).slice(0, 8))
  console.log(`  ${g.date}  keep ${g.keep}  drop ${g.drop.join(', ')}`);
