#!/usr/bin/env node
/**
 * Turns COROS's shared training plans into src/data/plans.ts.
 *
 * The share page is a JavaScript shell; the plan itself comes from
 * teamapi.coros.com, and every name in it is an i18n key ("P10004", "T3001")
 * resolved from the app's own English bundle.
 *
 * Units, which are not obvious: distance is centimetres, duration is seconds,
 * pace is milliseconds per kilometre, heart rate is plain bpm.
 *
 * What we take is the shape of the plan — the weeks, the distances, the pace
 * and heart-rate targets. What we do not take is COROS's prose: the wording on
 * this site is ours, and each plan credits and links to the original.
 *
 *   node scripts/import-plans.mjs
 */
import { writeFileSync } from 'node:fs';

const PLANS = [
  { id: '462503693697335296', slug: 'half-marathon-beginner-pace' },
  { id: '453112661276803072', slug: 'half-marathon-beginner-hr' },
  { id: '448633401730318357', slug: 'half-marathon-hr' },
  { id: '447892242034769926', slug: 'marathon-4-00-4-30' },
];

const LOCALE = 'https://static.coros.com/locale/coros-traininghub-v2/en-US.prod.js';
const DETAIL = (id) =>
  `https://teamapi.coros.com/training/plan/detail?supportRestExercise=1&id=${id}&region=1`;

const locale = await (await fetch(LOCALE)).text();
const strings = Object.fromEntries(
  [...locale.matchAll(/"((?:P|T)\d{3,6})"\s*:\s*"((?:[^"\\]|\\.)*)"/g)].map((m) => [m[1], m[2]])
);
const say = (key) => strings[key] ?? key;

const clock = (seconds) => {
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  return `${m}:${String(s).padStart(2, '0')}`;
};

/** A step's target: either a distance or a stretch of time. */
function target(ex) {
  if (ex.targetType === 5) return `${(ex.targetValue / 100000).toFixed(2).replace(/\.?0+$/, '')} km`;
  // Under a minute matters in this plan — the fast part of a strides session is
  // forty seconds, and "1 min" is both wrong and useless.
  if (ex.targetType === 2) {
    return ex.targetValue < 60 ? `${ex.targetValue} s` : `${Math.round(ex.targetValue / 60)} min`;
  }
  return '';
}

/**
 * And how hard: a pace band, a heart-rate band, or nothing in particular.
 *
 * The two ends are sorted, because COROS stores the recovery jog of a strides
 * session slow-end-first and it came out reading "7:43–6:11 /km".
 */
function effort(ex) {
  const [a, b] = [ex.intensityValue, ex.intensityValueExtend].sort((x, y) => x - y);
  if (ex.intensityType === 3 && a) return `${clock(a / 1000)}–${clock(b / 1000)} /km`;
  if (ex.intensityType === 2 && a) return `${a}–${b} bpm`;
  return '';
}

const KIND = { 1: 'warmup', 3: 'cooldown' };

const plans = [];
for (const { id, slug } of PLANS) {
  const body = await (await fetch(DETAIL(id), {
    headers: { Referer: 'https://training.coros.com/', 'User-Agent': 'Mozilla/5.0' },
  })).json();
  const d = body.data;
  const programs = new Map(d.programs.map((p) => [p.idInPlan, p]));

  const weeks = new Map();
  for (const entity of d.entities.sort((a, b) => a.dayNo - b.dayNo)) {
    const program = programs.get(entity.idInPlan);
    if (!program) continue;
    const n = Math.floor((entity.dayNo - 1) / 7) + 1;
    if (!weeks.has(n)) weeks.set(n, []);
    weeks.get(n).push({
      day: ((entity.dayNo - 1) % 7) + 1,
      name: say(program.name),
      km: +(program.distance / 100000).toFixed(2),
      minutes: Math.round(program.duration / 60),
      load: program.trainingLoad,
      steps: (program.exercises ?? []).map((ex) => {
        // An unnamed step with isGroup set is a repeat: it wraps the steps that
        // follow it and carries how many times they go round.
        if (ex.isGroup) {
          return { kind: 'repeat', label: `${ex.sets} ×`, target: '', effort: '' };
        }
        return {
          kind: KIND[ex.exerciseType] ?? 'work',
          label: say(ex.name),
          target: target(ex),
          effort: effort(ex),
        };
      }).filter((s) => s.kind === 'repeat' || s.target || s.effort),
    });
  }

  plans.push({
    slug,
    id,
    title: say(d.name),
    weeks: [...weeks.entries()]
      .sort((a, b) => a[0] - b[0])
      .map(([n, workouts]) => ({
        n,
        km: +workouts.reduce((t, w) => t + w.km, 0).toFixed(1),
        minutes: workouts.reduce((t, w) => t + w.minutes, 0),
        load: workouts.reduce((t, w) => t + w.load, 0),
        workouts,
      })),
  });
}

const ts = `// Generated by scripts/import-plans.mjs — do not edit by hand.
//
// The structure and figures of four COROS training plans: weeks, sessions,
// distances, and pace or heart-rate targets. The descriptions on the site are
// ours; each plan links to the COROS original, which is where these came from.

export interface Step {
  /** 'repeat' introduces the steps after it and says how many times. */
  kind: 'warmup' | 'work' | 'cooldown' | 'repeat';
  label: string;
  /** "4.83 km" or "5 min" */
  target: string;
  /** "5:28–6:10 /km" or "131–150 bpm", or empty where none is set. */
  effort: string;
}

export interface Workout {
  /** 1 = Monday. */
  day: number;
  name: string;
  km: number;
  minutes: number;
  /** COROS's training load for the session. */
  load: number;
  steps: Step[];
}

export interface Week {
  n: number;
  km: number;
  minutes: number;
  load: number;
  workouts: Workout[];
}

export interface Plan {
  slug: string;
  /** The plan on COROS, for the credit link. */
  id: string;
  title: string;
  weeks: Week[];
}

export const plans: Plan[] = ${JSON.stringify(plans, null, 2)};
`;
writeFileSync('src/data/plans.ts', ts);

for (const p of plans) {
  const km = p.weeks.reduce((t, w) => t + w.km, 0);
  console.log(`${p.title} — ${p.weeks.length} weeks, ${p.weeks.reduce((t,w)=>t+w.workouts.length,0)} sessions, ${Math.round(km)} km`);
}
