// Generated by scripts/fetch-weather.mjs — do not edit by hand.
//
// The weather each diary entry and race actually happened in, taken at the hour
// we were out rather than as a daily average. Source: Open-Meteo's historical
// archive for Yerevan (40.1792, 44.4991).

export interface Weather {
  /** The hour these figures are for, HH:MM local. */
  at: string;
  tempC: number;
  /** km/h */
  wind: number;
  sky: 'clear' | 'fair' | 'overcast' | 'fog' | 'drizzle' | 'rain' | 'snow' | 'showers' | 'thunder';
  snowCm?: number;
  rainMm?: number;
  /** Snow fell at some point that day, even if not while we were out. */
  snowedThatDay?: boolean;
  rainedThatDay?: boolean;
}

export const weather: Record<string, Weather> = {
  "2026-02-12": {
    "at": "21:00",
    "tempC": 1,
    "wind": 9,
    "sky": "fair",
    "rainedThatDay": true
  },
  "2026-03-05": {
    "at": "23:00",
    "tempC": 0,
    "wind": 5,
    "sky": "clear",
    "snowedThatDay": true
  },
  "2026-03-06": {
    "at": "21:00",
    "tempC": 4,
    "wind": 6,
    "sky": "overcast"
  },
  "2026-03-08": {
    "at": "10:00",
    "tempC": 2,
    "wind": 3,
    "sky": "overcast",
    "snowedThatDay": true
  },
  "2026-03-10": {
    "at": "23:00",
    "tempC": 0,
    "wind": 12,
    "sky": "clear"
  },
  "2026-03-11": {
    "at": "00:00",
    "tempC": 0,
    "wind": 13,
    "sky": "clear"
  },
  "2026-03-17": {
    "at": "23:00",
    "tempC": 7,
    "wind": 8,
    "sky": "clear"
  },
  "2026-03-21": {
    "at": "18:00",
    "tempC": 13,
    "wind": 6,
    "sky": "overcast",
    "rainedThatDay": true
  },
  "2026-03-28": {
    "at": "12:00",
    "tempC": 10,
    "wind": 3,
    "sky": "overcast",
    "rainedThatDay": true
  },
  "2026-03-29": {
    "at": "13:00",
    "tempC": 10,
    "wind": 9,
    "sky": "overcast",
    "rainedThatDay": true
  },
  "2026-04-02": {
    "at": "10:00",
    "tempC": 11,
    "wind": 4,
    "sky": "overcast",
    "rainedThatDay": true
  },
  "2026-04-04": {
    "at": "11:00",
    "tempC": 10,
    "wind": 7,
    "sky": "drizzle",
    "rainMm": 0.2,
    "rainedThatDay": true
  },
  "2026-04-11": {
    "at": "12:00",
    "tempC": 13,
    "wind": 6,
    "sky": "drizzle",
    "rainMm": 0.3,
    "rainedThatDay": true
  },
  "2026-04-14": {
    "at": "23:00",
    "tempC": 4,
    "wind": 5,
    "sky": "overcast",
    "rainedThatDay": true
  },
  "2026-04-15": {
    "at": "00:00",
    "tempC": 3,
    "wind": 7,
    "sky": "clear"
  },
  "2026-04-16": {
    "at": "10:00",
    "tempC": 8,
    "wind": 2,
    "sky": "clear"
  },
  "2026-05-01": {
    "at": "16:00",
    "tempC": 23,
    "wind": 6,
    "sky": "fair"
  },
  "2026-05-02": {
    "at": "12:00",
    "tempC": 19,
    "wind": 4,
    "sky": "clear"
  },
  "2026-05-04": {
    "at": "21:00",
    "tempC": 16,
    "wind": 5,
    "sky": "clear",
    "rainedThatDay": true
  },
  "2026-05-09": {
    "at": "22:00",
    "tempC": 15,
    "wind": 12,
    "sky": "clear"
  },
  "2026-05-10": {
    "at": "21:00",
    "tempC": 20,
    "wind": 9,
    "sky": "fair"
  },
  "2026-05-19": {
    "at": "23:00",
    "tempC": 13,
    "wind": 5,
    "sky": "fair"
  },
  "2026-05-21": {
    "at": "11:00",
    "tempC": 14,
    "wind": 2,
    "sky": "drizzle",
    "rainMm": 0.3,
    "rainedThatDay": true
  },
  "2026-05-23": {
    "at": "12:00",
    "tempC": 21,
    "wind": 3,
    "sky": "clear"
  },
  "2026-06-03": {
    "at": "21:00",
    "tempC": 22,
    "wind": 9,
    "sky": "clear"
  },
  "2026-06-07": {
    "at": "22:00",
    "tempC": 23,
    "wind": 20,
    "sky": "clear"
  },
  "2026-06-10": {
    "at": "00:00",
    "tempC": 18,
    "wind": 6,
    "sky": "clear",
    "rainedThatDay": true
  },
  "2026-06-14": {
    "at": "22:00",
    "tempC": 18,
    "wind": 2,
    "sky": "clear",
    "rainedThatDay": true
  },
  "2026-06-17": {
    "at": "01:00",
    "tempC": 21,
    "wind": 14,
    "sky": "clear"
  },
  "2026-06-18": {
    "at": "10:00",
    "tempC": 27,
    "wind": 3,
    "sky": "clear"
  },
  "2026-06-20": {
    "at": "10:00",
    "tempC": 28,
    "wind": 6,
    "sky": "clear"
  },
  "2026-06-25": {
    "at": "12:00",
    "tempC": 26,
    "wind": 3,
    "sky": "clear"
  },
  "2026-06-27": {
    "at": "08:00",
    "tempC": 21,
    "wind": 9,
    "sky": "fair"
  },
  "2026-06-28": {
    "at": "13:00",
    "tempC": 26,
    "wind": 7,
    "sky": "clear"
  },
  "2026-06-30": {
    "at": "23:00",
    "tempC": 23,
    "wind": 20,
    "sky": "clear"
  },
  "2026-07-02": {
    "at": "13:00",
    "tempC": 30,
    "wind": 4,
    "sky": "clear"
  },
  "2026-07-04": {
    "at": "21:00",
    "tempC": 24,
    "wind": 4,
    "sky": "drizzle",
    "rainMm": 0.4,
    "rainedThatDay": true
  },
  "2026-07-05": {
    "at": "10:00",
    "tempC": 23,
    "wind": 6,
    "sky": "drizzle",
    "rainMm": 0.1
  },
  "2026-07-08": {
    "at": "01:00",
    "tempC": 21,
    "wind": 4,
    "sky": "fair",
    "rainedThatDay": true
  },
  "2026-07-09": {
    "at": "11:00",
    "tempC": 25,
    "wind": 7,
    "sky": "clear"
  },
  "2026-07-11": {
    "at": "11:00",
    "tempC": 31,
    "wind": 7,
    "sky": "clear"
  },
  "2026-07-15": {
    "at": "12:00",
    "tempC": 33,
    "wind": 7,
    "sky": "clear"
  },
  "2026-07-16": {
    "at": "13:00",
    "tempC": 33,
    "wind": 4,
    "sky": "fair"
  },
  "2026-07-18": {
    "at": "07:00",
    "tempC": 22,
    "wind": 6,
    "sky": "clear"
  },
  "2026-07-28": {
    "at": "23:00",
    "tempC": 27,
    "wind": 29,
    "sky": "clear"
  },
  "2026-08-01": {
    "at": "10:00",
    "tempC": 29,
    "wind": 3,
    "sky": "clear"
  },
  "2026-08-02": {
    "at": "10:00",
    "tempC": 30,
    "wind": 2,
    "sky": "clear"
  },
  "2026-08-07": {
    "at": "17:00",
    "tempC": 34,
    "wind": 7,
    "sky": "fair"
  },
  "2026-08-08": {
    "at": "19:00",
    "tempC": 31,
    "wind": 26,
    "sky": "clear"
  },
  "2026-08-13": {
    "at": "12:00",
    "tempC": 31,
    "wind": 3,
    "sky": "clear"
  },
  "2026-08-15": {
    "at": "14:00",
    "tempC": 32,
    "wind": 4,
    "sky": "clear"
  },
  "2026-08-23": {
    "at": "17:00",
    "tempC": 37,
    "wind": 8,
    "sky": "clear"
  },
  "2026-08-24": {
    "at": "21:00",
    "tempC": 30,
    "wind": 25,
    "sky": "clear"
  },
  "2026-08-29": {
    "at": "13:00",
    "tempC": 30,
    "wind": 2,
    "sky": "clear"
  },
  "2026-09-01": {
    "at": "23:00",
    "tempC": 22,
    "wind": 12,
    "sky": "fair"
  },
  "2026-09-06": {
    "at": "14:00",
    "tempC": 30,
    "wind": 4,
    "sky": "fair",
    "rainedThatDay": true
  },
  "2026-09-08": {
    "at": "23:00",
    "tempC": 17,
    "wind": 17,
    "sky": "clear"
  }
};
